# == Schema Information
# Schema version: 20090623023153
#
# Table name: rights
#
#  id           :integer(4)      not null, primary key
#  controller   :string(255)
#  read_access  :boolean(1)
#  write_access :boolean(1)
#  role_id      :integer(4)
#  created_at   :datetime
#  updated_at   :datetime

class Right 

RIGHTS={"district_admin" =>
  [
  {:read_access=>true,
    :controller=>"district/users",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"district/schools",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"flag_descriptions",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"districts",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"district/students",
    :write_access=>true}
  ],
 "regular_user" => 
  [{:read_access=>true,
    :controller=>"custom_flags",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"recommendations",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/participants",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/categories",
    :write_access=>nil},
   {:read_access=>true,
    :controller=>"consultation_forms",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/comments",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/probes",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/objectives",
    :write_access=>nil},
   {:read_access=>true,
    :controller=>"team_consultations",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"custom_probes",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"principal_overrides",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/goals",
    :write_access=>nil},
   {:read_access=>true,
    :controller=>"reports",
    :write_access=>nil},
   {:read_access=>true,
    :controller=>"interventions/definitions",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"interventions/probe_assignments",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"schools",
    :write_access=>nil},
   {:read_access=>true,
    :controller=>"railmail",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"consultation_form_requests",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"checklists",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"students",
    :write_access=>nil},
   {:read_access=>true,
    :controller=>"student_comments",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"grouped_progress_entries",
    :write_access=>true}
  ],
 "school_admin" =>
  [{:read_access=>true,
    :controller=>"school_teams",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"team_schedulers",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"quicklist_items",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"schools",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"groups",
    :write_access=>true}],
 "content_admin" =>
  [{:read_access=>true,
    :controller=>"intervention_builder/recommended_monitors",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"intervention_builder/goals",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"checklist_builder/elements",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"intervention_builder/probes",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"intervention_builder/objectives",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"checklist_builder/questions",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"checklist_builder/checklists",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"intervention_builder/categories",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"checklist_builder/answers",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"intervention_builder/interventions",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"district/flag_categories",
    :write_access=>true},
   {:read_access=>true,
    :write_access=>true},
   {:read_access=>true,
    :controller=>"tiers",
    :write_access=>true},
   {:read_access=>true,
    :controller=>"railmail",
    :write_access=>true}],
 "state_admin" =>
  [{:read_access=>true,
    :controller=>"states",
    :write_access=>true}],
 "news_admin" =>
  [{:read_access=>true,
    :controller=>"news_items",
    :write_access=>true}],
 "country_admin" =>
  [{:read_access=>true,
    :controller=>"countries",
    :write_access=>true}]
}

  def self.cache_key
    RIGHTS.to_s.hash
  end

end
